# Generated by Django 4.2.10 on 2024-06-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDepartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(max_length=60, unique=True, verbose_name='Departamento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'config_departament',
                'ordering': ['pk'],
            },
        ),
    ]
