# Generated by Django 4.2.10 on 2024-10-22 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(choices=[('Endoscopia', 'Endoscopia'), ('Centro Cirúrgico', 'Centro Cirúrgico')], max_length=45, verbose_name='Instrumento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=12, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('operator', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Instrumentos',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'app_instrument',
                'ordering': ['instrument_name'],
                'unique_together': {('instrument_name', 'description')},
            },
        ),
    ]
