# Generated by Django 4.2.10 on 2024-10-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_departament', '0001_initial'),
        ('app_instrument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstrument',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config_departament.configdepartament', verbose_name='Departamento'),
        ),
    ]
