# Generated by Django 4.2.10 on 2024-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instrument', '0003_appinstrument_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstrument',
            name='instrument_name',
            field=models.CharField(max_length=45, verbose_name='Instrumento'),
        ),
    ]
