# Generated by Django 4.2.10 on 2024-06-06 18:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import message_private.models
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePrivate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(default=None, max_length=100)),
                ('content', ckeditor.fields.RichTextField(default=None)),
                ('attach_1', models.FileField(blank=True, null=True, upload_to=message_private.models.get_file_path, validators=[utils.validators.message_validate_file_extension])),
                ('attach_2', models.FileField(blank=True, null=True, upload_to=message_private.models.get_file_path, validators=[utils.validators.message_validate_file_extension])),
                ('attach_3', models.FileField(blank=True, null=True, upload_to=message_private.models.get_file_path, validators=[utils.validators.message_validate_file_extension])),
                ('attach_4', models.FileField(blank=True, null=True, upload_to=message_private.models.get_file_path, validators=[utils.validators.message_validate_file_extension])),
                ('flag_read_to', models.BooleanField(default=False, editable=False)),
                ('flag_read_recipient', models.BooleanField(default=False, editable=False)),
                ('flag_trash_to', models.BooleanField(default=False, editable=False)),
                ('flag_trash_recipient', models.BooleanField(default=False, editable=False)),
                ('flag_soft_excluded_to', models.BooleanField(default=False, editable=False)),
                ('flag_soft_excluded_recipient', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_recipient', to=settings.AUTH_USER_MODEL)),
                ('to_message', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_private',
                'ordering': ['flag_read_recipient', '-updated_at'],
            },
        ),
    ]
