# Generated by Django 4.2.10 on 2024-10-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instrument_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstrumentlog',
            name='instrument_id',
            field=models.CharField(default=1, max_length=36, verbose_name='ID Instrumento'),
            preserve_default=False,
        ),
    ]
