from .view_create_message_private import *
from .view_delete_message_private import *
from .view_detail_message_private import *
from .view_detail_message_private_read import *
from .view_detail_message_private_send import *
from .view_list_message_private import *
from .view_list_message_private_read import *
from .view_list_message_private_send import *
from .view_update_message_private_trash import *
from .view_list_message_private_trash import *
from .view_create_message_private_reply import *
from .view_update_message_private_soft_delete import *
from .view_update_message_private_restore import *
from .view_template_message_private_clean import *