# Generated by Django 4.2.10 on 2024-06-06 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('message', models.CharField(max_length=24, verbose_name='Mensagem')),
                ('type', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('danger', 'Atenção')], default='info', max_length=7, verbose_name='Tipo')),
                ('activated', models.BooleanField(default=True, verbose_name='Ativado')),
                ('operator', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notification',
                'ordering': ['title'],
            },
        ),
    ]
